
services:
  scraper:
    build: .
    command: python scraper.py
    env_file: .env
    volumes: [".:/app"]
  summarizer:
    build: .
    command: python summarizer.py
    env_file: .env
    volumes: [".:/app"]
  api:
    build: .
    command: uvicorn api_main:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes: [".:/app"]
    ports: ["8000:8000"]
